# We need Node.js to build our app
FROM node:16-alpine

# Update the package lists and install curl
RUN apk update && apk add curl

# Install .NET Core SDK for the React PreStart script  
RUN curl -SL --output dotnet.tar.gz https://download.visualstudio.microsoft.com/download/pr/9c86d7b4-acb2-4be4-8a89-d13bc3c3f28f/1d044c7c29df018e8f2837bb343e8a84/dotnet-sdk-7.0.304-linux-x64.tar.gz
# RUN dotnet_sha512='f4b7d0cde432bd37f445363b3937ad483e5006794886941e43124de051475925b3cd11313b73d2cae481ee9b8f131394df0873451f6088ffdbe73f150b1ed727'
# RUN echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c -
RUN mkdir -p /usr/share/dotnet
RUN tar -ozxf dotnet.tar.gz -C /usr/share/dotnet
RUN rm dotnet.tar.gz
RUN ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and yarn.lock
COPY package.json package-lock.json ./

# Install project dependencies
run npm install

# Copy local code to the container image
COPY . .

# Build application for production
RUN npm run build
RUN npm install -g serve

# Start server
CMD ["serve", "-s", "build"]

# Expose port
EXPOSE 3000
