# We need Node.js to build our app
FROM node:16-alpine as build

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install project dependencies
RUN yarn install --silent

# Copy local code to the container image
COPY . .

# Build the application
RUN yarn build

# Start from a small nginx image to serve our static files
FROM nginx:stable-alpine

# Copy static build directory from build stage to nginx image
COPY --from=build /app/build /usr/share/nginx/html

# Copy the nginx configuration file. This replaces the default.conf file in nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Start nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
