# We need Node.js to build our app
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install --silent

# Copy local code to the container image
COPY . .

# Start development server
CMD ["npm","run", "start"]

# Expose port
EXPOSE 3000
