# Base image# Base image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# Set the working directory
WORKDIR /src

# Copy and restore dependencies
COPY *.csproj .
RUN dotnet restore

# Copy the source code
COPY . .

# Publish the application
RUN dotnet publish -c release -o /src

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0

# Copy the published output from the build stage
COPY --from=build /src ./src

# Set environment variables
ENV ASPNETCORE_URLS=http://+:80

# Specify the entry point for the container
ENTRYPOINT ["dotnet", "/src/StarMax_BackEnd.dll"]