# Base image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# Set the working directory
WORKDIR /app

# Copy and restore dependencies
COPY *.csproj .
RUN dotnet restore

# Copy the source code
COPY . .

# Build the application in Debug configuration
RUN dotnet build -c Debug

# Publish the application
RUN dotnet publish -c Debug --output /app/publish

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime

# Set the working directory
WORKDIR /app

# Copy the published output from the build stage
COPY --from=build /app/publish .

# Expose port
EXPOSE 80

# Set the entry point
ENTRYPOINT ["dotnet", "StarMaxApp.dll"]
